### ISSUE TITLE
No reads mapped and juicer error

### ISSUE THREAD

**Issue by DaianeH** [XiaoTaoWang/pairLiftOver#3]
Hi,

I'd like to leftover a validPairs file from hg38 to hg19.

My input file looks like:

NS500488:301:H5MVMBGX2:2:13305:24468:17278      1       10174   +       22      50808109        -       NA      NA      NA      39      32
NS500488:301:H5MVMBGX2:3:12606:10597:6993       1       17495   +       6       329447  +       NA      NA      NA      48      60
NS500488:301:H5MVMBGX2:1:23306:13232:13066      1       121087  -       7       3651149 +       NA      NA      NA      44      60

The chromosome sizes file looks like:
chr1    249250621
chr2    243199373
chr3    198022430

My command is:

pairLiftOver --input MES_validPairs.txt.gz --input-format hic-pro --out-pre MES_lifted --output-format hic --out-chromsizes hg19.chrom.sizes --in-assembly hg38 --out-assembly hg19 --memory 40G

But I get the error:

numexpr.utils             INFO    @ 08/23/22 19:38:55: Note: detected 96 virtual cores but NumExpr set to maximum of 64, check "NUMEXPR_MAX_THREADS" environment variable.
numexpr.utils             INFO    @ 08/23/22 19:38:55: Note: NumExpr detected 96 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
numexpr.utils             INFO    @ 08/23/22 19:38:56: NumExpr defaulting to 8 threads.
pairLiftOver.utilities    INFO    @ 08/23/22 19:38:56: Writing headers ...
pairLiftOver.utilities    INFO    @ 08/23/22 19:39:00: Converting, sorting, and compressing ...
pairLiftOver.utilities    INFO    @ 08/23/22 19:43:45: 0 / 87,365,210 pairs were uniquely mapped to hg19
pairLiftOver.utilities    INFO    @ 08/23/22 19:43:45: Generate contact matrices using juicer at 2500000,1000000,500000,250000,100000,50000,25000,10000,5000 ...
WARN [2022-08-23T19:43:46,919]  [Globals.java:138] [main]  Development mode is enabled
Not including fragment map
Start preprocess
Writing header
Writing body
java.lang.RuntimeException: No reads in Hi-C contact matrices. This could be because the MAPQ filter is set too high (-q) or because all reads map to the same fragment.
        at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.mergeAndWriteBlocks(Preprocessor.java:1762)
        at juicebox.tools.utils.original.Preprocessor$MatrixZoomDataPP.access$000(Preprocessor.java:1531)
        at juicebox.tools.utils.original.Preprocessor.writeMatrix(Preprocessor.java:944)
        at juicebox.tools.utils.original.Preprocessor.writeBody(Preprocessor.java:661)
        at juicebox.tools.utils.original.Preprocessor.preprocess(Preprocessor.java:419)
        at juicebox.tools.clt.old.PreProcessing.run(PreProcessing.java:122)
        at juicebox.tools.HiCTools.main(HiCTools.java:96)
Traceback (most recent call last):
  File "/hpc/packages/minerva-centos7/py_packages/3.7/bin/pairLiftOver", line 137, in <module>
    run()
  File "/hpc/packages/minerva-centos7/py_packages/3.7/bin/pairLiftOver", line 133, in run
    high_res = args.high_res
  File "/hpc/packages/minerva-centos7/py_packages/3.7/lib/python3.7/site-packages/pairLiftOver/utilities.py", line 174, in liftover
    subprocess.check_call(' '.join(command), shell=True)
  File "/hpc/packages/minerva-centos7/python/3.7.3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'java -Xmx40g -jar /hpc/packages/minerva-centos7/py_packages/3.7/lib/python3.7/site-packages/pairLiftOver/data/juicer_tools_1.11.09_jcuda.0.8.jar pre -r 2500000,1000000,500000,250000,100000,50000,25000,10000,5000 /hiC/.pairliftover/MES_lifted.pairs.gz MES_lifted.hic hg19.chrom.sizes' returned non-zero exit status 56.

Any idea what is causing it and how to solve it?
Thank you,

**Comment by XiaoTaoWang** [comment]
I think the reason for this error is that in your validPairs file, there is no "chr" prefix in your chromosome label, but such prefix appears in both of your chromosome sizes file and the UCSC chain file.

**Comment by DaianeH** [comment]
That fixed it, thank you.
But another question: shouldn't the first column (the read name) be kept the same in the output file?
When I grep read names between files (before and after lifting over), I cannot find them.
Thanks,

**Comment by XiaoTaoWang** [comment]
pairLiftOver does keep the read names the same before and after lifting over. But note that the output pairs are re-sorted in a way so that they can be directly used to generate contact matrices using cooler or juicer.

If you cannot find a read name using for example this command ``zcat  MES_validPairs.txt.gz | grep "NS500488:301:H5MVMBGX2:2:13305:24468:17278"``, then this read might not be able to uniquely map between the two assemblies.

**Comment by DaianeH** [comment]
Got it.
I managed to lift over my validPairs file, but when I run FitHiC to identify significant interactions, I only get 1459 at q<0.05, while when running FitHiC on the original file not lifted over, I get 57037 contacts at q<0.05, so something went wrong with the lift over. Where can I start trouble shooting?

**Comment by XiaoTaoWang** [comment]
How many contact pairs in your original file, and how many contact pairs after lifting over?

**Comment by DaianeH** [comment]
Original file: 72979455
Lifted over:  72666530

**Comment by XiaoTaoWang** [comment]
Interesting ... the number looks reasonable between hg19 and hg38, but I have no idea why FitHiC is so different. In my test, I ran Peakachu and HiCCUPS, both software gave me very similar results between the matrix obtained from pairLiftOver and the matrix from read re-mapping.

In your case, I would suggest first plot a few regions and judge whether there are visually significant differences in those regions between the two matrices.

**Comment by DaianeH** [comment]
It's my first time processing HiC data. How do I perform this plotting?

I'm using fitHiC because I need to calculate the FDR of valid pairs to integrate these HiC data with GWAS summary statistics using FUMA (https://fuma.ctglab.nl), but FUMA only accepts hg19.

**Comment by XiaoTaoWang** [comment]
There are many choices, such as higlass, coolbox, and HiCExplorer. And several of my packages also include simple visualization module, such as TADLib (https://xiaotaowang.github.io/TADLib/visualize.html) and HiCPeaks (https://github.com/XiaoTaoWang/HiCPeaks)
